version: '4'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ticket_platform
      MYSQL_ROOT_PASSWORD: FAla12/?
    networks:
      - spring-demo

  mail-dev:
    image: maildev/maildev
    container_name: ticket-email
    restart: always
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-demo

  event-platform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-platform
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
      - mail-dev
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge
